#!/bin/bash -l
screen -X -S bobbot quit
PERL5LIB="/home/rendler/scripts:/home/rendler/perl5/lib:/home/rendler/Goose-master/lib"
export PERL5LIB=$PERL5LIB:$HOME/scripts:$HOME/perl5/lib:$HOME/perl5/lib/perl5
(cd /home/rendler/Bobbot && screen -S bobbot -t 0 -A -d -m ./bobbot-loop)
